version: '3.9'
services: 
    flaskr:
        image: gomy_bears_project
        build: 
            context: ./back
        environment: 
            FLASK_APP: flaskr/__init__.py
        ports: 
            - 8000:8000
        restart: always
        depends_on: 
            - postgres
            - ml
        command: bash -c "python manage.py create_db && python manage.py run -h 0.0.0.0 -p 8000"

    ml:
        image: ml_service
        build: 
            context: ./ml
        environment: 
            FLASK_APP: service/__init__.py
        ports: 
            - 8001:8001
        restart: always
        command: bash -c "python manage.py run -h 0.0.0.0 -p 8001"

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: ci_project
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASSWORD: ""
            POSTGRES_USER: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d ci_project"]
          interval: 30s
          timeout: 2s
          retries: 5
          start_period: 10s
        
volumes:
    postgres_data:
